import { Bot, Brain, Film, Images, LayoutDashboard, Sparkles, Video, type LucideIcon } from 'lucide-react';

export type ModulePack = 'core' | 'booster';
export type ModuleArea = 'home' | 'image' | 'video' | 'system';
export type ModuleStatus = 'verified' | 'lab' | 'parked';
export type SourceModuleId = 'core-shell' | 'z-image-studio' | 'chroma-image' | 'firered-image' | 'qwen-image' | 'wan-video' | 'ltx-video' | 'flux-klein';

export interface FeddaModule {
  id: string;
  sourceModuleId: SourceModuleId;
  label: string;
  description: string;
  area: ModuleArea;
  pack: ModulePack;
  enabled: boolean;
  tabs: string[];
  workflows?: string[];
  defaultTab: string;
  status?: ModuleStatus;
  statusLabel?: string;
  Icon: LucideIcon;
  card?: {
    poster?: string;
    video?: string;
  };
}

export const APP_VERSION_LABEL = 'FEDDA Hub v18';
export const ACTIVE_TAB_STORAGE_KEY = 'fedda_v18_active_tab';

const veniceCard = (index: number) => ({
  poster: `/cards/new/venice/${index}.jpeg`,
  video: `/cards/new/venice/${index}.mp4`,
});

export const FEDDA_MODULES: FeddaModule[] = [
  {
    id: 'image-studio',
    sourceModuleId: 'z-image-studio',
    label: 'Image Studio',
    description: 'Text, reference and LoRA-driven image workflows synced with ComfyUI.',
    area: 'home',
    pack: 'core',
    enabled: true,
    tabs: ['image'],
    defaultTab: 'image',
    Icon: Sparkles,
    card: veniceCard(1),
  },
  {
    id: 'video-studio',
    sourceModuleId: 'wan-video',
    label: 'Video Studio',
    description: 'WAN and LTX motion workflows with a consistent workbench layout.',
    area: 'home',
    pack: 'core',
    enabled: true,
    tabs: ['video'],
    defaultTab: 'video',
    Icon: Video,
    card: veniceCard(2),
  },
  {
    id: 'gallery',
    sourceModuleId: 'core-shell',
    label: 'Gallery',
    description: 'One unified place for generated images and videos.',
    area: 'system',
    pack: 'core',
    enabled: true,
    tabs: ['gallery'],
    defaultTab: 'gallery',
    Icon: Images,
    card: veniceCard(3),
  },
  {
    id: 'lora-character',
    sourceModuleId: 'core-shell',
    label: 'LoRA & Character',
    description: 'Install, import and manage LoRA character packs for active workflows.',
    area: 'system',
    pack: 'core',
    enabled: true,
    tabs: ['library'],
    defaultTab: 'library',
    Icon: LayoutDashboard,
    card: veniceCard(4),
  },
  {
    id: 'ollama-models',
    sourceModuleId: 'core-shell',
    label: 'Ollama Models',
    description: 'Download and remove local text and vision models used by FEDDA tools.',
    area: 'system',
    pack: 'core',
    enabled: true,
    tabs: ['ollama'],
    defaultTab: 'ollama',
    Icon: Bot,
    card: veniceCard(5),
  },
  {
    id: 'ui-agent',
    sourceModuleId: 'core-shell',
    label: 'UI Agent',
    description: 'Plan safe image and video workflow payloads from natural language.',
    area: 'system',
    pack: 'core',
    enabled: true,
    tabs: ['ui-agent'],
    defaultTab: 'ui-agent',
    Icon: Brain,
    card: veniceCard(6),
  },
  {
    id: 'z-image-basic',
    sourceModuleId: 'z-image-studio',
    label: 'Z-Image Txt2Img',
    description: 'Fast core text-to-image generation.',
    area: 'image',
    pack: 'core',
    enabled: true,
    tabs: ['z-image', 'z-image-txt2img'],
    workflows: ['z-image'],
    defaultTab: 'z-image-txt2img',
    status: 'verified',
    Icon: Sparkles,
    card: veniceCard(7),
  },
  {
    id: 'z-image-dual-lora',
    sourceModuleId: 'z-image-studio',
    label: 'Z-Image Dual LoRA',
    description: 'Two-person LoRA image with selected-person refinement.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['z-image-dual-lora'],
    workflows: ['z-image-dual-lora'],
    defaultTab: 'z-image-dual-lora',
    status: 'verified',
    Icon: Sparkles,
    card: veniceCard(8),
  },
  {
    id: 'chroma1-hd',
    sourceModuleId: 'chroma-image',
    label: 'Chroma1-HD',
    description: 'Official Lodestones Chroma1-HD text-to-image base workflow.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['chroma', 'chroma-txt2img'],
    workflows: ['chroma1-hd-txt2img'],
    defaultTab: 'chroma-txt2img',
    status: 'lab',
    statusLabel: 'Tuning',
    Icon: Sparkles,
    card: veniceCard(9),
  },
  {
    id: 'chroma-simple',
    sourceModuleId: 'chroma-image',
    label: 'Chroma Simple',
    description: 'Native Chroma comparison graph with softer defaults.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['chroma-simple-txt2img'],
    workflows: ['chroma-simple-txt2img'],
    defaultTab: 'chroma-simple-txt2img',
    status: 'lab',
    statusLabel: 'Tuning',
    Icon: Sparkles,
    card: veniceCard(10),
  },
  {
    id: 'flux2-klein',
    sourceModuleId: 'flux-klein',
    label: 'FLUX2-KLEIN',
    description: 'FLUX2-KLEIN 9B image generation.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['flux', 'flux-txt2img'],
    workflows: ['flux2klein-txt2img'],
    defaultTab: 'flux-txt2img',
    status: 'lab',
    statusLabel: 'Setup',
    Icon: Sparkles,
    card: veniceCard(11),
  },
  {
    id: 'firered-image-edit',
    sourceModuleId: 'firered-image',
    label: 'FireRed Edit',
    description: 'Instruction-based image editing with FireRed 1.1.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['firered-image-edit'],
    workflows: ['firered-image-edit'],
    defaultTab: 'firered-image-edit',
    status: 'verified',
    Icon: Sparkles,
    card: veniceCard(12),
  },
  {
    id: 'qwen-image',
    sourceModuleId: 'qwen-image',
    label: 'Qwen Image',
    description: 'Qwen text, reference and multi-angle image tools.',
    area: 'image',
    pack: 'booster',
    enabled: false,
    tabs: ['qwen', 'qwen-txt2img', 'qwen-image-ref', 'qwen-multi-angle'],
    workflows: ['qwen-edit-2512'],
    defaultTab: 'qwen-txt2img',
    status: 'parked',
    Icon: Sparkles,
    card: veniceCard(13),
  },
  {
    id: 'qwen-reference',
    sourceModuleId: 'qwen-image',
    label: 'Qwen Reference',
    description: 'Image-reference generation and edits.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['qwen-image-ref'],
    workflows: ['qwen-edit-2509-image-reference'],
    defaultTab: 'qwen-image-ref',
    status: 'lab',
    statusLabel: 'Test',
    Icon: Sparkles,
    card: veniceCard(14),
  },
  {
    id: 'qwen-rapid-edit-v23',
    sourceModuleId: 'qwen-image',
    label: 'Qwen Rapid Edit',
    description: 'Rapid AIO v23 NSFW image editing.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['qwen-rapid-edit-v23'],
    workflows: ['qwen-rapid-edit-v23'],
    defaultTab: 'qwen-rapid-edit-v23',
    status: 'verified',
    Icon: Sparkles,
    card: veniceCard(15),
  },
  {
    id: 'qwen-multi-angle',
    sourceModuleId: 'qwen-image',
    label: 'Qwen Multi Angle',
    description: 'Generate angle variants from one input.',
    area: 'image',
    pack: 'booster',
    enabled: true,
    tabs: ['qwen-multi-angle'],
    workflows: ['qwen-multi-angles', 'qwen-multi-angles-fast'],
    defaultTab: 'qwen-multi-angle',
    status: 'verified',
    Icon: Sparkles,
    card: veniceCard(16),
  },
  {
    id: 'wan22-img2vid',
    sourceModuleId: 'wan-video',
    label: 'WAN 2.2 Img2Vid',
    description: 'Animate a still image with WAN 2.2.',
    area: 'video',
    pack: 'booster',
    enabled: true,
    tabs: ['wan22-img2vid'],
    workflows: ['wan22-img2vid'],
    defaultTab: 'wan22-img2vid',
    status: 'lab',
    statusLabel: 'Test',
    Icon: Video,
    card: veniceCard(18),
  },
  {
    id: 'wan22-vid2vid',
    sourceModuleId: 'wan-video',
    label: 'WAN 2.2 Vid2Vid',
    description: 'Transform and extend a video clip.',
    area: 'video',
    pack: 'booster',
    enabled: true,
    tabs: ['wan22-vid2vid'],
    workflows: ['wan22-vid2vid'],
    defaultTab: 'wan22-vid2vid',
    status: 'lab',
    statusLabel: 'Test',
    Icon: Video,
    card: veniceCard(19),
  },
  {
    id: 'wan22-story',
    sourceModuleId: 'wan-video',
    label: 'WAN Story',
    description: 'Build video from a six-frame story sequence.',
    area: 'video',
    pack: 'booster',
    enabled: true,
    tabs: ['wan22-img2vid-6frames'],
    workflows: ['wan22-img2vid-6frames'],
    defaultTab: 'wan22-img2vid-6frames',
    status: 'lab',
    statusLabel: 'Test',
    Icon: Video,
    card: veniceCard(20),
  },
  {
    id: 'steady-dancer',
    sourceModuleId: 'wan-video',
    label: 'Steady Dancer',
    description: 'Transfer dance motion from reference video.',
    area: 'video',
    pack: 'booster',
    enabled: true,
    tabs: ['wan21-steady-dancer'],
    workflows: ['wan21-steady-dancer', 'z-image-controlnet-pose'],
    defaultTab: 'wan21-steady-dancer',
    status: 'lab',
    statusLabel: 'Build',
    Icon: Video,
    card: veniceCard(21),
  },
  {
    id: 'ltx-img2vid',
    sourceModuleId: 'ltx-video',
    label: 'LTX Img2Vid',
    description: 'Animate one reference image with LTX.',
    area: 'video',
    pack: 'booster',
    enabled: true,
    tabs: ['ltx', 'ltx-img2vid'],
    workflows: ['ltx-img2vid'],
    defaultTab: 'ltx-img2vid',
    status: 'verified',
    Icon: Film,
    card: veniceCard(22),
  },
  {
    id: 'ltx-first-last',
    sourceModuleId: 'ltx-video',
    label: 'LTX First / Last',
    description: 'Interpolate motion between two keyframes.',
    area: 'video',
    pack: 'booster',
    enabled: true,
    tabs: ['ltx-flf'],
    workflows: ['ltx-flf'],
    defaultTab: 'ltx-flf',
    status: 'verified',
    Icon: Film,
    card: veniceCard(23),
  },
];

export const ENABLED_MODULES = FEDDA_MODULES.filter((module) => module.enabled);
export const HOME_MODULES = ENABLED_MODULES.filter((module) => module.card && (module.area === 'home' || module.area === 'system'));
export const IMAGE_WORKFLOW_MODULES = ENABLED_MODULES.filter((module) => module.area === 'image' && module.card);
export const VIDEO_WORKFLOW_MODULES = ENABLED_MODULES.filter((module) => module.area === 'video' && module.card);

export const VALID_TABS = new Set(ENABLED_MODULES.flatMap((module) => module.tabs));

export const PAGE_META = Object.fromEntries(
  ENABLED_MODULES.flatMap((module) =>
    module.tabs.map((tab) => [tab, { label: module.label, Icon: module.Icon }]),
  ),
);

export const DEFAULT_TAB = IMAGE_WORKFLOW_MODULES[0]?.defaultTab || 'image';
